import { HolidayMilestone, Post } from '../types';

export const HOLIDAY_MILESTONES: HolidayMilestone[] = [
  {
    id: 'halloween',
    name: 'Halloween Spooktacular',
    date: '2026-10-31',
    category: 'cultural',
    suggestedPhase: 'teaser',
    description: 'Q4 holiday kick-off, costume themes, flash treats',
    badgeColor: 'bg-amber-100 text-amber-900 border-amber-300',
  },
  {
    id: 'singles_day',
    name: "Singles' Day (11/11)",
    date: '2026-11-11',
    category: 'ecommerce',
    suggestedPhase: 'early_access',
    description: 'Global mega-sale day, treat-yourself campaigns',
    badgeColor: 'bg-indigo-100 text-indigo-800 border-indigo-300',
  },
  {
    id: 'early_bf',
    name: 'Early Black Friday VIP',
    date: '2026-11-20',
    category: 'major_retail',
    suggestedPhase: 'early_access',
    description: 'Email list & VIP early bird discount drops',
    badgeColor: 'bg-blue-100 text-blue-900 border-blue-300',
  },
  {
    id: 'thanksgiving',
    name: 'Thanksgiving',
    date: '2026-11-26',
    category: 'cultural',
    suggestedPhase: 'teaser',
    description: 'Gratitude posts, holiday sneak peeks, countdown teasers',
    badgeColor: 'bg-amber-100 text-amber-900 border-amber-300',
  },
  {
    id: 'black_friday',
    name: 'Black Friday 🛍️',
    date: '2026-11-27',
    category: 'major_retail',
    suggestedPhase: 'black_friday',
    description: 'Biggest shopping day of the year, main doorbuster offers',
    badgeColor: 'bg-slate-900 text-white border-slate-700',
  },
  {
    id: 'small_biz_sat',
    name: 'Small Business Saturday',
    date: '2026-11-28',
    category: 'ecommerce',
    suggestedPhase: 'black_friday',
    description: 'Support small & local makers, behind-the-scenes stories',
    badgeColor: 'bg-sky-100 text-sky-800 border-sky-300',
  },
  {
    id: 'cyber_monday',
    name: 'Cyber Monday ⚡',
    date: '2026-11-30',
    category: 'major_retail',
    suggestedPhase: 'cyber_monday',
    description: 'Online exclusive discounts, digital bundles, free shipping',
    badgeColor: 'bg-blue-600 text-white border-blue-700',
  },
  {
    id: 'giving_tuesday',
    name: 'Giving Tuesday 💖',
    date: '2026-12-01',
    category: 'cultural',
    suggestedPhase: 'general',
    description: 'Charity partnerships, donation match, community giveback',
    badgeColor: 'bg-indigo-50 text-indigo-900 border-indigo-200',
  },
  {
    id: 'green_monday',
    name: 'Green Monday',
    date: '2026-12-14',
    category: 'ecommerce',
    suggestedPhase: 'holiday_gifting',
    description: 'Second-chance December shopping peak, gift guide curations',
    badgeColor: 'bg-teal-100 text-teal-900 border-teal-300',
  },
  {
    id: 'shipping_deadline',
    name: 'Last Day for Standard Shipping 📦',
    date: '2026-12-18',
    category: 'shipping',
    suggestedPhase: 'shipping_deadline',
    description: 'Urgent cutoff warning: order today to arrive before Christmas',
    badgeColor: 'bg-rose-100 text-rose-900 border-rose-300',
  },
  {
    id: 'super_saturday',
    name: 'Super Saturday (Panic Saturday)',
    date: '2026-12-19',
    category: 'major_retail',
    suggestedPhase: 'last_chance',
    description: 'Final weekend before Christmas, digital gift cards & express shipping',
    badgeColor: 'bg-blue-100 text-blue-900 border-blue-300',
  },
  {
    id: 'christmas_eve',
    name: 'Christmas Eve & Hanukkah',
    date: '2026-12-24',
    category: 'cultural',
    suggestedPhase: 'christmas',
    description: 'Warm holiday greetings, instant e-gift cards, brand appreciation',
    badgeColor: 'bg-blue-900 text-blue-50 border-blue-700',
  },
  {
    id: 'christmas_day',
    name: 'Christmas Day 🎄',
    date: '2026-12-25',
    category: 'cultural',
    suggestedPhase: 'christmas',
    description: 'Pure holiday celebration and festive wishes',
    badgeColor: 'bg-indigo-900 text-indigo-50 border-indigo-700',
  },
  {
    id: 'boxing_day',
    name: 'Boxing Day / End-of-Year Sale',
    date: '2026-12-26',
    category: 'major_retail',
    suggestedPhase: 'boxing_day',
    description: 'Year-end inventory clearance, spend holiday gift money',
    badgeColor: 'bg-sky-100 text-sky-800 border-sky-300',
  },
  {
    id: 'new_year_eve',
    name: "New Year's Eve 🥂",
    date: '2026-12-31',
    category: 'cultural',
    suggestedPhase: 'new_year',
    description: 'Year in review, best moments, gratitude, celebratory mood',
    badgeColor: 'bg-slate-900 text-white border-slate-700',
  },
  {
    id: 'new_year_day',
    name: "New Year's Day 2027 ✨",
    date: '2027-01-01',
    category: 'cultural',
    suggestedPhase: 'new_year',
    description: 'Fresh start resolutions, new collections, vision for the year',
    badgeColor: 'bg-sky-100 text-sky-800 border-sky-300',
  },
];

export const HOLIDAY_HASHTAG_PACKS = [
  {
    title: 'Black Friday / Cyber Week',
    tags: '#BlackFriday #BlackFridayDeals #CyberMonday #CyberWeek #HolidaySale #DoorbusterDeals #ShopSmall #BlackFriday2026',
  },
  {
    title: 'Holiday Gift Guides',
    tags: '#HolidayGiftGuide #GiftsForHer #GiftsForHim #StockingStuffers #UniqueGifts #HolidayShopping #WishList #GiftIdeas',
  },
  {
    title: 'Shipping & Urgency',
    tags: '#LastChance #HolidayCutoff #OrderEarly #FastShipping #HolidayRush #GiftCard #InstantGift',
  },
  {
    title: 'Festive & Winter Vibes',
    tags: '#HolidaySeason #TisTheSeason #CozyVibes #WinterAesthetic #FestiveMood #HolidayMagic #MerryAndBright',
  },
  {
    title: 'New Year & Boxing Day',
    tags: '#BoxingDay #EndofYearSale #NewYearNewMe #FreshStart #HolidayWrapUp #ClearanceSale #Hello2027',
  },
];

// Sample demo starter posts for immediate visualization
export function getSampleStarterPosts(): Post[] {
  const currentYear = new Date().getFullYear();
  return [
    {
      id: 'sample_1',
      title: '🎁 Holiday Gift Guide Drop',
      scheduledDate: `${currentYear}-11-18`,
      scheduledTime: '10:00',
      platform: 'instagram',
      caption: `The 2026 Holiday Gift Guide is officially live! ✨ We've hand-selected our top crowd-pleasers, stocking stuffers, and limited-edition bundles to make shopping effortless.\n\nTap the link in bio to browse the full curated catalogue before popular sizes sell out. Which piece is at the top of your wishlist? Drop a comment below! 👇`,
      hashtags: '#HolidayGiftGuide #HolidayShopping #StockingStuffers #GiftInspo #TisTheSeason #HolidayPreview',
      status: 'ready',
      campaignPhase: 'holiday_gifting',
      callToAction: 'Tap link in bio to explore the Gift Guide',
      linkUrl: 'https://example.com/gift-guide',
      internalNotes: 'Use warm lifestyle carousel photography. Pin top comment with direct category links.',
      gridOrderIndex: 1,
      media: [
        {
          id: 'media_sample_1',
          dataUrl: 'https://images.unsplash.com/photo-1513885535751-8b9238bd345a?w=800&q=80',
          filename: 'gift_guide_cover.jpg',
          aspectRatio: '1:1',
          altText: 'Festive wrapped holiday presents with golden ribbon',
        },
      ],
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: 'sample_2',
      title: '⚡ VIP Early Access Black Friday',
      scheduledDate: `${currentYear}-11-24`,
      scheduledTime: '09:00',
      platform: 'instagram',
      caption: `SHHH... early doors are open! 🤫 Our VIP subscribers get exclusive 48-hour head-start access to Black Friday pricing: 35% off site-wide with code VIPEARLY.\n\nNo crowds, no stock sell-outs. Secure your favorites right now before the public sale goes live on Friday.`,
      hashtags: '#BlackFridayEarlyAccess #VIPAccess #BlackFridaySale #CyberWeek #ExclusiveDeals',
      status: 'scheduled',
      campaignPhase: 'early_access',
      callToAction: 'Use code VIPEARLY at checkout',
      linkUrl: 'https://example.com/vip-sale',
      internalNotes: 'Ensure discount code VIPEARLY is active at 8:45 AM.',
      gridOrderIndex: 2,
      media: [
        {
          id: 'media_sample_2',
          dataUrl: 'https://images.unsplash.com/photo-1607082348824-0a96f2a4b9da?w=800&q=80',
          filename: 'black_friday_vip.jpg',
          aspectRatio: '1:1',
          altText: 'Black Friday shopping bag and gold confetti',
        },
      ],
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: 'sample_3',
      title: '🛍️ Black Friday Main Event Launch',
      scheduledDate: `${currentYear}-11-27`,
      scheduledTime: '00:01',
      platform: 'instagram',
      caption: `IT IS HERE. Our biggest event of the year is officially LIVE! 🖤\n\nEnjoy up to 40% OFF site-wide + free gift packaging on all orders placed today. Stock is strictly limited on bestsellers—once they're gone, they won't restock until 2027.\n\nLink in bio to shop now.`,
      hashtags: '#BlackFriday2026 #BlackFridaySale #HolidaySavings #ShopTheSale #Doorbuster',
      status: 'ready',
      campaignPhase: 'black_friday',
      callToAction: 'Shop site-wide up to 40% OFF',
      linkUrl: 'https://example.com/black-friday',
      internalNotes: 'Schedule for 12:01 AM. Update Instagram bio link to sale landing page.',
      gridOrderIndex: 3,
      media: [
        {
          id: 'media_sample_3',
          dataUrl: 'https://images.unsplash.com/photo-1543258103-a62bdc069871?w=800&q=80',
          filename: 'bf_midnight_launch.jpg',
          aspectRatio: '1:1',
          altText: 'Minimal dark luxury holiday packaging',
        },
      ],
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: 'sample_4',
      title: '✨ Small Business Saturday Story',
      scheduledDate: `${currentYear}-11-28`,
      scheduledTime: '11:00',
      platform: 'instagram',
      caption: `Behind every small brand is a person doing a happy dance when an order comes in! 💃\n\nThank you for choosing independent makers this season. Every order keeps our dream going, supports fair wages, and delivers handcrafted quality directly to your doorstep. Share your favorite small business in the comments! 💛`,
      hashtags: '#SmallBusinessSaturday #ShopSmall #SupportSmallBusiness #Handcrafted #MakersGonnaMake',
      status: 'draft',
      campaignPhase: 'black_friday',
      callToAction: 'Tell us your favorite small shop below',
      linkUrl: '',
      internalNotes: 'Authentic founder / team photo behind the scenes packing boxes.',
      gridOrderIndex: 4,
      media: [
        {
          id: 'media_sample_4',
          dataUrl: 'https://images.unsplash.com/photo-1526178613552-2b45c6c302f0?w=800&q=80',
          filename: 'behind_the_scenes.jpg',
          aspectRatio: '1:1',
          altText: 'Artisan crafting handmade package with twine',
        },
      ],
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: 'sample_5',
      title: '⚡ Cyber Monday Flash BOGO',
      scheduledDate: `${currentYear}-11-30`,
      scheduledTime: '08:30',
      platform: 'instagram',
      caption: `24 HOURS ONLY: Buy One, Get One 50% Off site-wide with code CYBERMONDAY! ⚡💻\n\nThe ultimate chance to grab gifts for everyone on your list and treat yourself too. Offer expires tonight at 11:59 PM EST.`,
      hashtags: '#CyberMonday #CyberMondayDeals #BOGOSale #HolidayDeals #FlashSale',
      status: 'scheduled',
      campaignPhase: 'cyber_monday',
      callToAction: 'Use code CYBERMONDAY today only',
      linkUrl: 'https://example.com/cyber-deals',
      internalNotes: 'Run countdown sticker on Instagram stories every 4 hours.',
      gridOrderIndex: 5,
      media: [
        {
          id: 'media_sample_5',
          dataUrl: 'https://images.unsplash.com/photo-1512909006721-3d6018887383?w=800&q=80',
          filename: 'cyber_monday_sparkle.jpg',
          aspectRatio: '1:1',
          altText: 'Sparkling holiday decorations with laptop shopping',
        },
      ],
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: 'sample_6',
      title: '📦 Shipping Cutoff Reminder',
      scheduledDate: `${currentYear}-12-18`,
      scheduledTime: '12:00',
      platform: 'instagram',
      caption: `⏰ FINAL CALL FOR GUARANTEED CHRISTMAS DELIVERY! Today is the hard cutoff for standard shipping to arrive by December 24th.\n\nDon't let holiday delays ruin the surprise—place your orders before 5:00 PM EST today to ensure under-the-tree arrival! 🎄✨`,
      hashtags: '#HolidayShipping #OrderCutoff #ChristmasCountdown #HolidayShopping #LastCall',
      status: 'draft',
      campaignPhase: 'shipping_deadline',
      callToAction: 'Order by 5 PM EST for guaranteed Christmas delivery',
      linkUrl: 'https://example.com/shipping-dates',
      internalNotes: 'Post prominently across feed and stories.',
      gridOrderIndex: 6,
      media: [
        {
          id: 'media_sample_6',
          dataUrl: 'https://images.unsplash.com/photo-1543589077-47d81606c1bf?w=800&q=80',
          filename: 'shipping_deadline_box.jpg',
          aspectRatio: '1:1',
          altText: 'Brown kraft holiday shipping box with pine cones',
        },
      ],
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
  ];
}
